[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  # --- perbaikan ---
  # Baris ini memberitahu Netlify untuk menyertakan
  # semua file dari folder 'utils' saat mendeploy fungsi.
  included_files = ["netlify/utils/**"]

# Environment variables for build
[build.environment]
  CI = "false"
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
